version: '3.8'

services:
  frontend:
    build:
      context: ./quiz
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=example
      - DB_NAME=liveapp
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: liveapp
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
