version: '3.8'

services:
  frontend:
    build:
      context: ./quiz
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=nomicosecitta
      - SOCKET_ORIGIN=http://localhost:3000
