version: '3.8'

services:
  frontend:
    build: ./quiz
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_SOCKET_URL=http://localhost:5000
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=nomicosecitta
      - SOCKET_ORIGIN=http://localhost:3000
    restart: unless-stopped
